### ISSUE TITLE
Multiple Error Messages when Run

### ISSUE THREAD

**Issue by LibertyGuy62** [CCoffie/AD-Locked-Out-Users#1]
I'm running on W7 64 bit. I've run the KB. 
I get this error multiple times when unlocking an account. (But it does unlock the user account).

---
## DataGridView Default Error Dialog

The following exception occurred in the DataGridView:

System.Management.Automation.PSArgumentNullException: Cannot process argument because the value of argument "component" is null. Change the value of argument "component" to a non-null value.

   at System.Management.Automation.PSObjectPropertyDescriptor.GetValue(Object component)

   at System.Windows.Forms.DataGridView.DataGridViewDataConnection.GetValue(Int32 boundColumnIndex, Int32 columnIndex, Int32 rowIndex)

**Comment by CCoffie** [comment]
Is this happening with all users? or just one specific user?

**Comment by LibertyGuy62** [comment]
All users. And again, the account does successfully unlock.

**Comment by LibertyGuy62** [comment]
More info. This only happens when double clicking on the last remaining user in the list. Every time.

**Comment by dneuman1** [comment]
I have a potential fix for this issue, but would need Caleb to review my addition to his code.
